package com.example.Material_Mitra.enums;

public enum ResultStatus {
    NEW_CANDIDATE,
    PENDING,       
	SCHEDULED,
    INTERVIEWED,
    PLACED,
    REJECTED,
    NOT_INTERESTED,
    HOLD,
    HIGH_CTC,
    DROPPED_BY_CLIENT,
    
    SUBMITTED_TO_CLIENT,
    NO_RESPONSE,
    IMMEDIATE,
    REJECTED_BY_CLIENT,
    CLIENT_SHORTLIST,
    FIRST_INTERVIEW_SCHEDULED,
    FIRST_INTERVIEW_FEEDBACK_PENDING,
    FIRST_INTERVIEW_REJECT,
    
    
    SECOND_INTERVIEW_SCHEDULED,
    SECOND_INTERVIEW_FEEDBACK_PENDING,
    SECOND_INTERVIEW_REJECT,
    
    
    THIRD_INTERVIEW_SCHEDULED,
    THIRD_INTERVIEW_FEEDBACK_PENDING,
    THIRD_INTERVIEW_REJECT,
    
    INTERNEL_REJECT,
    CLIENT_REJECT,
    FINAL_SELECT,
    JOINED,
    BACKEDOUT,
    NOT_RELEVANT
    
}
	