name: Deploy Spring Boot App to AWS EC2

on:
  push:
    branches:
      - main   # or 'master' if your main branch name is master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Decode SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no target/Material_Mitra-0.0.1-SNAPSHOT.jar ubuntu@3.82.57.164:/home/ubuntu/
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@3.82.57.164 << 'EOF'
            sudo fuser -k 8080/tcp || true
            nohup java -jar /home/ubuntu/Material_Mitra-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          EOF
